CREATE TABLE BOOK (
	BOK_NO NUMBER NOT NULL,
	BOK_NANE VARCHAR2(30) NOT NULL,
	BOK_PRICE NUMBER,
	BOK_YEAR DATE NOT NULL,
	PUB_NO NUMBER
);

COMMENT ON TABLE BOOK IS '도서';

COMMENT ON COLUMN BOOK.BOK_NO IS '도서번호';

COMMENT ON COLUMN BOOK.BOK_NANE IS '도서이름';

COMMENT ON COLUMN BOOK.BOK_PRICE IS '도서단가';

COMMENT ON COLUMN BOOK.BOK_YEAR IS '발행년도';

COMMENT ON COLUMN BOOK.PUB_NO IS '출판사번호';

CREATE UNIQUE INDEX PK_BOOK
	ON BOOK (
		BOK_NO ASC
	);

ALTER TABLE BOOK
	ADD
		CONSTRAINT PK_BOOK
		PRIMARY KEY (
			BOK_NO
		);

CREATE TABLE PUBLISHER (
	PUB_NO NUMBER NOT NULL,
	PUB_NAME VARCHAR2(20) NOT NULL,
	PUB_CHAEGER VARCHAR2(20),
	PUB_TEL VARCHAR2(30),
	PUB_ADDR VARCHAR2(255)
);

COMMENT ON TABLE PUBLISHER IS '출판사';

COMMENT ON COLUMN PUBLISHER.PUB_NO IS '출판사번호';

COMMENT ON COLUMN PUBLISHER.PUB_NAME IS '출판사이름';

COMMENT ON COLUMN PUBLISHER.PUB_CHAEGER IS '담당자';

COMMENT ON COLUMN PUBLISHER.PUB_TEL IS '전화번호';

COMMENT ON COLUMN PUBLISHER.PUB_ADDR IS '주소';

CREATE UNIQUE INDEX PK_PUBLISHER
	ON PUBLISHER (
		PUB_NO ASC
	);

ALTER TABLE PUBLISHER
	ADD
		CONSTRAINT PK_PUBLISHER
		PRIMARY KEY (
			PUB_NO
		);

CREATE TABLE ORDERS (
	ORD_NO NUMBER NOT NULL,
	CUS_NO NUMBER,
	ORD_DATE DATE NOT NULL,
	ORD_QTY NUMBER NOT NULL,
	ORD_AMOUNT NUMBER NOT NULL,
	BOK_NO NUMBER
);

COMMENT ON TABLE ORDERS IS '주문';

COMMENT ON COLUMN ORDERS.ORD_NO IS '주문번호';

COMMENT ON COLUMN ORDERS.CUS_NO IS '고객번호';

COMMENT ON COLUMN ORDERS.ORD_DATE IS '주문일자';

COMMENT ON COLUMN ORDERS.ORD_QTY IS '주문수량';

COMMENT ON COLUMN ORDERS.ORD_AMOUNT IS '주문금액';

COMMENT ON COLUMN ORDERS.BOK_NO IS '도서번호';

CREATE UNIQUE INDEX PK_ORDERS
	ON ORDERS (
		ORD_NO ASC
	);

ALTER TABLE ORDERS
	ADD
		CONSTRAINT PK_ORDERS
		PRIMARY KEY (
			ORD_NO
		);

CREATE TABLE CUSTOMER (
	CUS_NO NUMBER NOT NULL,
	CUS_NAME VARCHAR2(20) NOT NULL,
	CUS_TEL VARCHAR2(30) NOT NULL,
	CUS_ADDR VARCHAR2(255)
);

COMMENT ON TABLE CUSTOMER IS '고객';

COMMENT ON COLUMN CUSTOMER.CUS_NO IS '고객번호';

COMMENT ON COLUMN CUSTOMER.CUS_NAME IS '고객이름';

COMMENT ON COLUMN CUSTOMER.CUS_TEL IS '전화번호';

COMMENT ON COLUMN CUSTOMER.CUS_ADDR IS '주소';

CREATE UNIQUE INDEX PK_CUSTOMER
	ON CUSTOMER (
		CUS_NO ASC
	);

ALTER TABLE CUSTOMER
	ADD
		CONSTRAINT PK_CUSTOMER
		PRIMARY KEY (
			CUS_NO
		);

ALTER TABLE BOOK
	ADD
		CONSTRAINT FK_PUBLISHER_TO_BOOK
		FOREIGN KEY (
			PUB_NO
		)
		REFERENCES PUBLISHER (
			PUB_NO
		);

ALTER TABLE ORDERS
	ADD
		CONSTRAINT FK_BOOK_TO_ORDERS
		FOREIGN KEY (
			BOK_NO
		)
		REFERENCES BOOK (
			BOK_NO
		);

ALTER TABLE ORDERS
	ADD
		CONSTRAINT FK_CUSTOMER_TO_ORDERS
		FOREIGN KEY (
			CUS_NO
		)
		REFERENCES CUSTOMER (
			CUS_NO
		);